/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.projekat.forme;

import rs.ac.bg.fon.nprog.projekat.domen.Klijent;
import rs.ac.bg.fon.nprog.projekat.domen.Ploca;
import rs.ac.bg.fon.nprog.projekat.domen.StavkaZaduzenja;
import rs.ac.bg.fon.nprog.projekat.domen.Zaduzenje;
import rs.ac.bg.fon.nprog.projekat.domen.Zaposleni;
import static java.awt.image.ImageObserver.HEIGHT;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import rs.ac.bg.fon.nprog.projekat.klaseZaKomunikaciju.KlijentskiZahtev;
import rs.ac.bg.fon.nprog.projekat.kontroler.Kontroler;
import rs.ac.bg.fon.nprog.projekat.modeli.ModelStavkiZaduzenja;
import rs.ac.bg.fon.nprog.projekat.modeli.ModelTabeleZaduzenja;
import rs.ac.bg.fon.nprog.projekat.operacije.Operacije;

/**
 *
 * @author Ignjat
 */
public class DodajZaduzenje extends javax.swing.JFrame {

    /**
     * Creates new form DodajZaduzenje
     */
    public DodajZaduzenje() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        popuniListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        cmbKlijenti = new javax.swing.JComboBox<>();
        cmbZaposleni = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eDatum = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        cmbPloce = new javax.swing.JComboBox<>();
        eBrojPloca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        btnDodajStavku = new javax.swing.JButton();
        btnIzbrisiStavku = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Klijent:");

        jLabel2.setText("Zaposleni:");

        eDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel3.setText("Datum:");

        btnSave.setText("Kreiraj zaduzenje");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        eBrojPloca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eBrojPlocaKeyTyped(evt);
            }
        });

        jLabel4.setText("Broj ploca:");

        jLabel5.setText("Ploca:");

        jLabel7.setText("Cena Zaduzenja :");

        lblCena.setText("0");

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnIzbrisiStavku.setText("Izbrisi stavku");
        btnIzbrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbZaposleni, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKlijenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbPloce, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eBrojPloca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnDodajStavku)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnIzbrisiStavku)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPloce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eBrojPloca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzbrisiStavku))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");

            Date datum = format.parse(eDatum.getText());

            Klijent kl = (Klijent) cmbKlijenti.getSelectedItem();
            Zaposleni zp = (Zaposleni) cmbZaposleni.getSelectedItem();

            Zaduzenje zaduzenje = new Zaduzenje();
            zaduzenje.setDatum(datum);
            zaduzenje.setKlijent(kl);
            zaduzenje.setZaposleni(zp);
            zaduzenje.setUkupno(BigDecimal.ZERO);
            ModelStavkiZaduzenja x = (ModelStavkiZaduzenja) tblStavke.getModel();
            ArrayList<StavkaZaduzenja> stavke = x.getStavke();
            if (stavke.size() == 0) {
                JOptionPane.showMessageDialog(this, "Niste uneli nijednu stavku", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.KREIRAJ_ZADUZENJE,zaduzenje );
            KlijentskiZahtev kz2 = new KlijentskiZahtev(Operacije.DODAJ_STAVKU_ZADUZENJA, x.getStavke());

            Kontroler.getInstance().kreirajZaduzenje(kz);
            
            Kontroler.getInstance().dodajStavkuZaduzenja(kz2);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Neispravni podaci", "Greska", JOptionPane.ERROR_MESSAGE);
        }


                    }//GEN-LAST:event_btnSaveActionPerformed

    public void izracunajCenu() {
        ModelStavkiZaduzenja x = (ModelStavkiZaduzenja) tblStavke.getModel();
        ArrayList<StavkaZaduzenja> stavke = x.getStavke();
        BigDecimal cena = new BigDecimal(0);

        for (StavkaZaduzenja sz : stavke) {
            System.out.println(sz.getVrednost());
            cena = cena.add(sz.getVrednost());
            System.out.println(cena);

        }
        lblCena.setText(cena.toString());

    }
    private void eBrojPlocaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eBrojPlocaKeyTyped

    }//GEN-LAST:event_eBrojPlocaKeyTyped

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        try {
            Ploca ploca = (Ploca) cmbPloce.getSelectedItem();
            int kolicina = Integer.parseInt(eBrojPloca.getText());
            BigDecimal cena = new BigDecimal(kolicina).multiply(ploca.getCenaIzdavanja()).setScale(2, RoundingMode.CEILING);

            StavkaZaduzenja stavka = new StavkaZaduzenja();
            Klijent kl = (Klijent) cmbKlijenti.getSelectedItem();
            Zaposleni zp = (Zaposleni) cmbZaposleni.getSelectedItem();
            stavka.setKlijent(kl);
            stavka.setZaposleni(zp);
            stavka.setKolicina(kolicina);
            stavka.setPloca(ploca);
            stavka.setVrednost(cena);
            ModelStavkiZaduzenja x = (ModelStavkiZaduzenja) tblStavke.getModel();
            x.dodajStavku(stavka);
            x.fireTableDataChanged();
            izracunajCenu();
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Neispravan broj ploca", "Greska", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnIzbrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiStavkuActionPerformed
        try {
            ModelStavkiZaduzenja x = (ModelStavkiZaduzenja) tblStavke.getModel();
            x.izbrisiStavku(tblStavke.getSelectedRow());

            x.fireTableDataChanged();
            izracunajCenu();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Morate selektovati stavku", "Greska", JOptionPane.ERROR_MESSAGE);

        }
     }//GEN-LAST:event_btnIzbrisiStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajZaduzenje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzbrisiStavku;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Klijent> cmbKlijenti;
    private javax.swing.JComboBox<Ploca> cmbPloce;
    private javax.swing.JComboBox<Zaposleni> cmbZaposleni;
    private javax.swing.JTextField eBrojPloca;
    private javax.swing.JFormattedTextField eDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblStavke;
    // End of variables declaration//GEN-END:variables

    private void popuniListe() {
        lblID.setText("Vas ID je : " + Kontroler.getInstance().getPrijavljeniZaposleni().getSifraNaloga());
        ArrayList<Ploca> ploce = Kontroler.getInstance().vratiSvePloce();
        cmbPloce.setModel(new DefaultComboBoxModel(ploce.toArray()));

        ArrayList<Klijent> klijenti = Kontroler.getInstance().vratiSveKlijente();
        ArrayList<Zaposleni> zaposleni = Kontroler.getInstance().vratiSveZaposlene();
        System.out.println(zaposleni);
        cmbKlijenti.setModel(new DefaultComboBoxModel(klijenti.toArray()));
        cmbZaposleni.setModel(new DefaultComboBoxModel(zaposleni.toArray()));

        ModelStavkiZaduzenja mtb = new ModelStavkiZaduzenja();
        tblStavke.setModel(mtb);
    }
}
