/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.projekat.forme;

import static java.awt.image.ImageObserver.HEIGHT;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import rs.ac.bg.fon.nprog.projekat.kontroler.Kontroler;

/**
 *
 * @author Ignjat
 */
public class PocetnaForma extends javax.swing.JFrame {

	/**
	 * Creates new form PocetnaForma
	 */
	public PocetnaForma() {
		initComponents();
		// kontroler.Kontroler.getInstance().setPocetnaForma(this);
		srediFormu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lblUsername = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		lblDobrodosli = new javax.swing.JLabel();
		lblID = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JPopupMenu.Separator();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JPopupMenu.Separator();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblDobrodosli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		lblDobrodosli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		lblID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

		jMenu1.setText("Sistemske Operacije");

		jMenuItem1.setText("Dodaj novu plocu");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("Pretrazi/Promeni/Izbrisi ploce");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("Unesi novo zaduzenje");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem5.setText("Pretrazi/Promeni/Izbrisi zaduzenje");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem5);
		jMenu1.add(jSeparator2);

		jMenuItem4.setText("Ucitajte bazu u JSON fajl");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem4);

		jMenuItem7.setText("Ucitajte JSON fajl u bazu");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem7);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Opcije");
		jMenu2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenu2ActionPerformed(evt);
			}
		});

		jMenuItem6.setText("Odjavi se");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem6);
		jMenu2.add(jSeparator1);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblDobrodosli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 71, Short.MAX_VALUE).addComponent(jLabel1).addGap(320,
								320, 320))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup().addComponent(lblUsername).addGap(54, 54,
														54))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup()
														.addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE,
																103, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblUsername)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(61, 61, 61).addComponent(jLabel1)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(18, 18, 18).addComponent(lblDobrodosli,
										javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(56, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {

		DodajPlocu dp = new DodajPlocu();
		dp.setVisible(true);

	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		PretragaPloca pp = new PretragaPloca();
		pp.setVisible(true);

	}

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		DodajZaduzenje dz = new DodajZaduzenje();
		dz.setVisible(true);
	}

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		PretragaZaduzenja pz = new PretragaZaduzenja();
		pz.setVisible(true);

	}

	private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {

		ImageIcon icon = new ImageIcon("src/main/java/rs/ac/bg/fon/nprog/projekat/images/success.png");

		if (JOptionPane.showConfirmDialog(rootPane, "Da li ste sigurni da zelite da se odjavite") != 0)
			return;
		JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili", "Info", JOptionPane.INFORMATION_MESSAGE, icon);
		this.setVisible(false);
		LoginForma lf = new LoginForma();
		lf.setVisible(true);
	}

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("U JSON");
		Kontroler.getInstance().ploceUJSON();
	}

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		Kontroler.getInstance().JSONUPloce();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PocetnaForma().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JPopupMenu.Separator jSeparator1;
	private javax.swing.JPopupMenu.Separator jSeparator2;
	private javax.swing.JLabel lblDobrodosli;
	private javax.swing.JLabel lblID;
	private javax.swing.JLabel lblUsername;
	// End of variables declaration

	private void srediFormu() {

//		lblDobrodosli.setText(
//				Kontroler.getInstance().getPrijavljeniZaposleni().getZaposleni().toString() + ", dobrodosli na sistem");
//		lblID.setText("Vas ID je : " + Kontroler.getInstance().getPrijavljeniZaposleni().getSifraNaloga());
	}
}
