/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.nprog.projekat.forme;

import rs.ac.bg.fon.nprog.projekat.domen.Ploca;
import static java.awt.image.ImageObserver.HEIGHT;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import rs.ac.bg.fon.nprog.projekat.klaseZaKomunikaciju.KlijentskiZahtev;
import rs.ac.bg.fon.nprog.projekat.kontroler.Kontroler;
import rs.ac.bg.fon.nprog.projekat.operacije.Operacije;

/**
 *
 * @author Ignjat
 */
public class PretragaPloca extends javax.swing.JFrame {

    /**
     * Creates new form PretragaPloca
     */
    public PretragaPloca() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        initalState();
        Kontroler.getInstance().setPretragaForma(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNaziv = new javax.swing.JTextField();
        eAutor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eId = new javax.swing.JTextField();
        eCena = new javax.swing.JTextField();
        eAutorV = new javax.swing.JTextField();
        eNazivV = new javax.swing.JTextField();
        eBrojPesama = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        eSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        eDatum = new javax.swing.JFormattedTextField();
        lblID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv ploce:");

        jLabel2.setText("Autor:");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jLabel3.setText("Broj pesama");

        jLabel4.setText("Naziv ploce");

        jLabel5.setText("Autor");

        jLabel6.setText("Datum izdavanja");

        jLabel7.setText("Cena iznajmljivanja");

        jLabel8.setText("ID ploce");

        eId.setEditable(false);
        eId.setEnabled(false);

        btnIzmeni.setText("Izmeni podatke");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        eSave.setText("Sacuvaj izmene");
        eSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Izbrisi plocu");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        eDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eNaziv)
                            .addComponent(eAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(eDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnPretrazi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(btnIzmeni)
                                .addGap(43, 43, 43)
                                .addComponent(eSave)))
                        .addGap(134, 134, 134)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eBrojPesama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(eNazivV, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(eAutorV, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(eCena, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnIzmeni)
                            .addComponent(eSave)))
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnPretrazi)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNazivV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eAutorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eBrojPesama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String naziv = eNaziv.getText();
        String autor = eAutor.getText();

        if (naziv.isEmpty() || autor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti ispravne podatke", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Ploca pl = new Ploca();
        pl.setNaziv(naziv);
        pl.setAutor(autor);
        pl = Kontroler.getInstance().pretraziPlocu(new KlijentskiZahtev(Operacije.PRETRAZI_PLOCE, pl));

        if (pl == null) {
            JOptionPane.showMessageDialog(this, "Ploca nije pronadjena", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        eAutorV.setText(pl.getAutor());
        eNazivV.setText(pl.getNaziv());
        eCena.setText(pl.getCenaIzdavanja().toString());
        eDatum.setText(pl.getDatumIzdavanja().toString());
        eId.setText(String.valueOf(pl.getIdPloce()));
        eBrojPesama.setText(String.valueOf(pl.getBrojPesama()));


    }//GEN-LAST:event_btnPretraziActionPerformed

    public void initalState() {
        lblID.setText("Vas ID je : " +Kontroler.getInstance().getPrijavljeniZaposleni().getSifraNaloga());

        eAutorV.setText("");
        eNazivV.setText("");
        eCena.setText("");
        eDatum.setText("");
        eId.setText("");
        eBrojPesama.setText("");
        eAutor.setText("");
        eNaziv.setText("");

        eAutorV.setEnabled(false);
        eNazivV.setEnabled(false);
        eCena.setEnabled(false);
        eDatum.setEnabled(false);
        eId.setEnabled(false);
        eBrojPesama.setEnabled(false);
    }
    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (eId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nijedna ploca nije ucitana", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        eAutorV.setEnabled(true);
        eNazivV.setEnabled(true);
        eCena.setEnabled(true);
        eDatum.setEnabled(true);
        eId.setEnabled(true);
        eBrojPesama.setEnabled(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void eSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSaveActionPerformed

        if (eId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nijedna ploca nije ucitana", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            String autor = eAutorV.getText();
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");

            Date datumIzdavanja = format.parse(eDatum.getText());

            int brojPesama = Integer.parseInt(eBrojPesama.getText());
            int id = Integer.parseInt(eId.getText());
            BigDecimal cenaIzdavanja = new BigDecimal(eCena.getText());

            String naziv = eNazivV.getText();
            Ploca ploca = new Ploca();
            ploca.setAutor(autor);
            ploca.setNaziv(naziv);
            ploca.setBrojPesama(brojPesama);
            ploca.setCenaIzdavanja(cenaIzdavanja);
            ploca.setDatumIzdavanja(datumIzdavanja);
            ploca.setIdPloce(id);

            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.IZMENI_PLOCU, ploca);
            Kontroler.getInstance().izmeniPlocu(kz);
            initalState();

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Neispravni podaci", "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Neispravni podaci", "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_eSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (eId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nijedna ploca nije ucitana", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Ploca ploca = new Ploca();
        ploca.setIdPloce(Integer.parseInt(eId.getText()));

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.IZBRISI_PLOCU, ploca);
        Kontroler.getInstance().izbrisiPlocu(kz);
        initalState();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaPloca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaPloca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaPloca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaPloca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaPloca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JTextField eAutor;
    private javax.swing.JTextField eAutorV;
    private javax.swing.JTextField eBrojPesama;
    private javax.swing.JTextField eCena;
    private javax.swing.JFormattedTextField eDatum;
    private javax.swing.JTextField eId;
    private javax.swing.JTextField eNaziv;
    private javax.swing.JTextField eNazivV;
    private javax.swing.JButton eSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblID;
    // End of variables declaration//GEN-END:variables
}
